# Generated by Django 3.0.3 on 2020-04-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(blank=True, default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=200)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, default='0', null=True)),
                ('path', models.CharField(default='brand', max_length=200)),
                ('small_image', models.ImageField(blank=True, upload_to='images/brand')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(blank=True, max_length=200)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('year', models.IntegerField(blank=True, default='1980', null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('small_image', models.ImageField(blank=True, upload_to='images/machine')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('sort_order', models.IntegerField(blank=True, default='0', null=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PartDiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_diagram', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/part')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=200)),
                ('path', models.CharField(default='series', max_length=200)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('small_image', models.ImageField(blank=True, upload_to='images/series')),
                ('sort_order', models.IntegerField(blank=True, default='0', null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Brand')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PartList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partlist', models.CharField(blank=True, max_length=200)),
                ('upload', models.FileField(blank=True, upload_to='pdfs')),
                ('machine', models.ManyToManyField(to='app_websites.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, max_length=200)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('ref_no', models.IntegerField(blank=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Assembly')),
                ('machine', models.ManyToManyField(blank=True, to='app_websites.Machine')),
                ('part_diagram', models.ManyToManyField(blank=True, to='app_websites.PartDiagram')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('path', models.CharField(default='series', max_length=200)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('small_image', models.ImageField(blank=True, upload_to='images/model')),
                ('header_image', models.ImageField(blank=True, upload_to='images/model')),
                ('sort_order', models.IntegerField(blank=True, default='0', null=True)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Series')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Model'),
        ),
        migrations.AddField(
            model_name='brand',
            name='machine_type',
            field=models.ManyToManyField(to='app_websites.MachineType'),
        ),
    ]
