# Generated by Django 3.0.3 on 2020-05-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='small_image',
            field=models.ImageField(blank=True, upload_to='media/images/brand'),
        ),
    ]
