# Generated by Django 3.0.3 on 2020-04-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0002_auto_20200405_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='partlist',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Category2'),
        ),
    ]
