# Generated by Django 3.0.3 on 2020-04-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0003_partlist_category2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='position',
        ),
        migrations.AddField(
            model_name='brand',
            name='sort_order',
            field=models.IntegerField(default='0'),
        ),
    ]
