# Generated by Django 3.0.3 on 2020-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0004_partlistsection_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='part',
            name='link',
        ),
        migrations.AlterField(
            model_name='part',
            name='part_diagram',
            field=models.ManyToManyField(blank=True, to='app_websites.PartListSection'),
        ),
    ]
