# Generated by Django 3.0.3 on 2020-04-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0007_auto_20200408_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(default='', max_length=200)),
                ('brand', models.ManyToManyField(to='app_websites.Brand')),
            ],
            options={
                'ordering': ['machine_type'],
            },
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
