# Generated by Django 3.0.3 on 2020-05-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0007_auto_20200513_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartDiagram',
        ),
        migrations.AlterField(
            model_name='partlistsection',
            name='part_diagram',
            field=models.ImageField(blank=True, upload_to='images/part'),
        ),
    ]
