# Generated by Django 3.0.3 on 2020-05-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0008_auto_20200513_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partlist',
            name='machine',
            field=models.ManyToManyField(blank=True, to='app_websites.Machine'),
        ),
    ]
