# Generated by Django 3.0.3 on 2020-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0008_auto_20200408_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinetype',
            name='brand',
        ),
        migrations.AddField(
            model_name='brand',
            name='machine_type',
            field=models.ManyToManyField(to='app_websites.MachineType'),
        ),
    ]
