# Generated by Django 3.0.3 on 2020-04-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0009_auto_20200408_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinetype',
            options={},
        ),
        migrations.RenameField(
            model_name='machinetype',
            old_name='machine_type',
            new_name='name',
        ),
    ]
