# Generated by Django 3.0.3 on 2020-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0009_auto_20200513_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='partlistsection',
            name='partlist',
            field=models.ManyToManyField(blank=True, to='app_websites.PartList'),
        ),
    ]
