# Generated by Django 3.0.3 on 2020-05-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0010_partlistsection_partlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='link',
        ),
    ]
