# Generated by Django 3.0.3 on 2020-04-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0011_auto_20200410_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetype',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
