# Generated by Django 3.0.3 on 2020-05-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0011_remove_part_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_diagram',
            new_name='partlist_section',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='ref_no',
            new_name='sort_order',
        ),
        migrations.RemoveField(
            model_name='part',
            name='assembly',
        ),
    ]
