# Generated by Django 3.0.3 on 2020-05-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0012_auto_20200513_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='machine',
        ),
    ]
