# Generated by Django 3.0.3 on 2020-04-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0012_machinetype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinetype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
