# Generated by Django 3.0.3 on 2020-04-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0013_auto_20200410_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='category1',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
