# Generated by Django 3.0.3 on 2020-05-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0013_remove_part_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partlist',
            name='machine',
        ),
    ]
