# Generated by Django 3.0.3 on 2020-05-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0014_remove_partlist_machine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='sort_order',
            new_name='item_no',
        ),
    ]
