# Generated by Django 3.0.3 on 2020-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0016_auto_20200513_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='partlist_section',
        ),
        migrations.RemoveField(
            model_name='partlistsection',
            name='partlist',
        ),
        migrations.AddField(
            model_name='partlistsection',
            name='part',
            field=models.ManyToManyField(to='app_websites.Part'),
        ),
    ]
