# Generated by Django 3.0.3 on 2020-04-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0016_auto_20200411_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Brand'),
        ),
    ]
