# Generated by Django 3.0.3 on 2020-04-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0017_series_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_path',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
