# Generated by Django 3.0.3 on 2020-04-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0018_series_series_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='series_path',
            field=models.CharField(default='series', max_length=200),
        ),
    ]
