# Generated by Django 3.0.3 on 2020-04-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0021_auto_20200411_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
    ]
