# Generated by Django 3.0.3 on 2020-04-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0023_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='machine',
            name='year',
        ),
        migrations.AddField(
            model_name='machine',
            name='year',
            field=models.ManyToManyField(to='app_websites.Year'),
        ),
    ]
