# Generated by Django 3.0.3 on 2020-04-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0025_series_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(),
        ),
    ]
