# Generated by Django 3.0.3 on 2020-04-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0026_auto_20200413_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='short_decsription',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
