# Generated by Django 3.0.3 on 2020-04-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0027_series_short_decsription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='short_decsription',
        ),
        migrations.AddField(
            model_name='series',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
