# Generated by Django 3.0.3 on 2020-04-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0028_auto_20200413_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='sort_order',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
