# Generated by Django 3.0.3 on 2020-04-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0029_series_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='small_image',
            field=models.ImageField(blank=True, default='no-small-image.jpg', null=True, upload_to=''),
        ),
    ]
