# Generated by Django 3.0.3 on 2020-04-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0030_series_small_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='path',
            field=models.CharField(default='brand', max_length=200),
        ),
    ]
