# Generated by Django 3.0.3 on 2020-04-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0033_auto_20200415_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='small_image',
            field=models.ImageField(blank=True, default='no-small-image.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='model',
            name='sort_order',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
