# Generated by Django 3.0.3 on 2020-04-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0034_auto_20200415_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='category1',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='machinetype',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='short_description',
            new_name='short_desc',
        ),
        migrations.RenameField(
            model_name='partlist',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='short_description',
            new_name='short_desc',
        ),
    ]
