# Generated by Django 3.0.3 on 2020-04-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0035_auto_20200415_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='header_image',
            field=models.ImageField(blank=True, default='no-small-image.jpg', null=True, upload_to=''),
        ),
    ]
