# Generated by Django 3.0.3 on 2020-04-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0036_model_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='small_image',
            field=models.ImageField(blank=True, default='no-small-image.jpg', null=True, upload_to=''),
        ),
    ]
