# Generated by Django 3.0.3 on 2020-04-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0037_auto_20200415_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='start_year',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
