# Generated by Django 3.0.3 on 2020-04-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0042_auto_20200417_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='small_image',
            field=models.ImageField(blank=True, default='no-small-image.jpg', null=True, upload_to=''),
        ),
    ]
