# Generated by Django 3.0.3 on 2020-04-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0044_auto_20200417_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='year_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='year_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
