# Generated by Django 3.0.3 on 2020-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0046_auto_20200417_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='year_from',
            field=models.IntegerField(blank=True, default='1980', null=True),
        ),
    ]
