# Generated by Django 3.0.3 on 2020-04-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0047_auto_20200417_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='year_from',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='year_to',
        ),
        migrations.AddField(
            model_name='machine',
            name='start_year',
            field=models.IntegerField(blank=True, choices=[(1980, 'Y1980'), (1981, 'Y1981'), (1982, 'Y1982'), (1983, 'Y1983'), (1984, 'Y1984'), (1985, 'Y1985'), (1986, 'Y1986'), (1987, 'Y1987'), (1988, 'Y1988'), (1989, 'Y1989')], default='1980', null=True),
        ),
    ]
