# Generated by Django 3.0.3 on 2020-04-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0048_auto_20200417_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='from_year',
            field=models.IntegerField(blank=True, default='1980', null=True),
        ),
    ]
