# Generated by Django 3.0.3 on 2020-04-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0049_machine_from_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='to_year',
            field=models.IntegerField(blank=True, default='1980', null=True),
        ),
    ]
