# Generated by Django 3.0.3 on 2020-04-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0050_machine_to_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='start_year',
        ),
    ]
