# Generated by Django 3.0.3 on 2020-04-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0051_remove_machine_start_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='year',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
