# Generated by Django 3.0.3 on 2020-04-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0052_auto_20200417_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinetype',
            old_name='name',
            new_name='machine_type',
        ),
    ]
