# Generated by Django 3.0.3 on 2020-04-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0053_auto_20200417_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetype',
            name='sort_order',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
