# Generated by Django 3.0.3 on 2020-04-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0054_machinetype_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinetype',
            options={'ordering': ['sort_order']},
        ),
        migrations.CreateModel(
            name='PartList_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='url', max_length=200)),
                ('machine_type', models.ManyToManyField(to='app_websites.Machine')),
            ],
        ),
    ]
