# Generated by Django 3.0.3 on 2020-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0055_auto_20200417_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='partlist_temp',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='partlist_temp',
            name='machine_type',
            field=models.ManyToManyField(to='app_websites.MachineType'),
        ),
    ]
