# Generated by Django 3.0.3 on 2020-04-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0057_remove_partlist_temp_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partlist_temp',
            name='machine_type',
            field=models.ManyToManyField(to='app_websites.Machine'),
        ),
    ]
