# Generated by Django 3.0.3 on 2020-04-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0060_delete_partlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartList_temp',
            new_name='PartList',
        ),
    ]
