# Generated by Django 3.0.3 on 2020-04-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0061_auto_20200418_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partlist',
            old_name='machine_type',
            new_name='machine',
        ),
    ]
