# Generated by Django 3.0.3 on 2020-04-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0062_auto_20200418_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['from_year']},
        ),
        migrations.AddField(
            model_name='model',
            name='variant',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
