# Generated by Django 3.0.3 on 2020-04-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0063_auto_20200418_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='has_variant',
            field=models.BooleanField(default=False),
        ),
    ]
