# Generated by Django 3.0.3 on 2020-04-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0064_machine_has_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='has_variant',
        ),
        migrations.RemoveField(
            model_name='model',
            name='variant',
        ),
        migrations.AddField(
            model_name='machine',
            name='machine',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
