# Generated by Django 3.0.3 on 2020-04-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0065_auto_20200418_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='small_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='model',
            name='header_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='model',
            name='small_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
