# Generated by Django 3.0.3 on 2020-04-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0066_auto_20200419_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='small_image',
            field=models.ImageField(blank=True, upload_to='media/brand'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='small_image',
            field=models.ImageField(blank=True, upload_to='media/machine'),
        ),
        migrations.AlterField(
            model_name='model',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='media/model'),
        ),
        migrations.AlterField(
            model_name='model',
            name='small_image',
            field=models.ImageField(blank=True, upload_to='media/model'),
        ),
        migrations.AlterField(
            model_name='series',
            name='small_image',
            field=models.ImageField(blank=True, upload_to='media/series'),
        ),
    ]
