# Generated by Django 3.0.3 on 2020-04-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0068_auto_20200419_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='partlist',
            name='path',
        ),
        migrations.AddField(
            model_name='partlist',
            name='upload',
            field=models.FileField(blank=True, upload_to='images/model'),
        ),
    ]
