# Generated by Django 3.0.3 on 2020-04-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0069_auto_20200419_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partlist',
            name='upload',
            field=models.FileField(blank=True, upload_to='pdfs'),
        ),
    ]
