# Generated by Django 3.0.3 on 2020-04-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0073_auto_20200419_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='path',
            field=models.CharField(default='series', max_length=200),
        ),
    ]
