# Generated by Django 3.0.3 on 2020-04-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0074_machine_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, max_length=200)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('diagram_number', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='part',
            field=models.ManyToManyField(to='app_websites.Part'),
        ),
    ]
