# Generated by Django 3.0.3 on 2020-04-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0075_auto_20200420_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='part',
            field=models.ManyToManyField(blank=True, to='app_websites.Part'),
        ),
    ]
