# Generated by Django 3.0.3 on 2020-04-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0076_auto_20200420_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
