# Generated by Django 3.0.3 on 2020-04-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0077_auto_20200420_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='diagram_number',
            new_name='ref_no',
        ),
    ]
