# Generated by Django 3.0.3 on 2020-04-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0078_auto_20200420_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
