# Generated by Django 3.0.3 on 2020-04-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0079_part_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='part',
        ),
        migrations.AddField(
            model_name='part',
            name='machine',
            field=models.ManyToManyField(blank=True, to='app_websites.Machine'),
        ),
    ]
