# Generated by Django 3.0.3 on 2020-04-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0080_auto_20200420_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartDiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_diagram', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='part_diagram',
            field=models.ManyToManyField(blank=True, to='app_websites.PartDiagram'),
        ),
    ]
