# Generated by Django 3.0.3 on 2020-04-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0081_auto_20200420_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdiagram',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/part'),
        ),
    ]
