# Generated by Django 3.0.3 on 2020-04-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0082_partdiagram_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category2',
        ),
    ]
