# Generated by Django 3.0.3 on 2020-04-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0084_auto_20200422_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='partlist',
            name='assembly',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Assembly'),
            preserve_default=False,
        ),
    ]
