# Generated by Django 3.0.3 on 2020-04-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0085_partlist_assembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partlist',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Assembly'),
        ),
    ]
