# Generated by Django 3.0.3 on 2020-04-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0086_auto_20200422_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partlist',
            name='assembly',
        ),
    ]
