# Generated by Django 3.0.3 on 2020-04-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0087_remove_partlist_assembly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assembly',
        ),
    ]
