# Generated by Django 3.0.3 on 2020-04-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0089_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
