# Generated by Django 3.0.3 on 2020-04-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0090_auto_20200422_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='partlist',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Assembly'),
        ),
    ]
