# Generated by Django 3.0.3 on 2020-04-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0091_partlist_assembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='sort_order',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
