# Generated by Django 3.0.3 on 2020-04-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0092_assembly_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='machine',
        ),
        migrations.AddField(
            model_name='machine',
            name='part',
            field=models.ManyToManyField(blank=True, to='app_websites.Part'),
        ),
    ]
