# Generated by Django 3.0.3 on 2020-04-22 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0095_remove_machine_to_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['year']},
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='from_year',
            new_name='year',
        ),
    ]
