# Generated by Django 3.0.3 on 2020-04-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0096_auto_20200422_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partlist',
            name='assembly',
        ),
        migrations.AddField(
            model_name='part',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_websites.Assembly'),
        ),
    ]
