# Generated by Django 3.0.3 on 2020-04-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0097_auto_20200423_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partlist',
            name='desc',
        ),
    ]
